# Generated by Django 3.2.17 on 2024-08-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramstatistics',
            name='social_media_use',
            field=models.JSONField(default=None, null=True),
        ),
    ]
