# Generated by Django 3.2.17 on 2024-09-15 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_instagramstatistics_social_media_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookStatistics',
            fields=[
                ('instagramstatistics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.instagramstatistics')),
            ],
            bases=('reports.instagramstatistics',),
        ),
    ]
