# Generated by Django 3.2.4 on 2021-07-10 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0023_auto_20210620_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightBox',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='mainpage_highlightbox', serialize=False, to='cms.cmsplugin')),
                ('title', models.TextField(default='')),
                ('text', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
