# Generated by Django 3.2.4 on 2021-07-13 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightBox',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='mainpage_highlightbox', serialize=False, to='cms.cmsplugin')),
                ('title', models.TextField(default='')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(blank=True)),
                ('alignment', models.CharField(choices=[('none', 'none'), ('right', 'right'), ('left', 'left')], default='none', max_length=10)),
                ('background', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_image', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
