# Generated by Django 3.2.4 on 2021-07-11 10:27

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightbox',
            name='background',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_image', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
