# Generated by Django 3.2.4 on 2021-07-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightbox',
            name='external_image',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
