# Generated by Django 3.2.13 on 2022-05-19 12:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_basicpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', icon='title')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('list', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(label='List'), icon='list-ul')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('highlight', wagtail.blocks.StructBlock([('title', wagtail.blocks.RichTextBlock()), ('text', wagtail.blocks.RichTextBlock()), ('background', wagtail.images.blocks.ImageChooserBlock(required=False)), ('alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'left'), ('right', 'right')]))]))], use_json_field=True),
        ),
    ]
