# Generated by Django 3.2.4 on 2021-07-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_highlightbox_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightbox',
            name='alignment',
            field=models.CharField(choices=[('right', 'right'), ('left', 'left')], default='left', max_length=10),
        ),
    ]
