# Generated by Django 3.2.4 on 2021-07-11 10:55

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_highlightbox_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightbox',
            name='text',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True),
        ),
    ]
