# Generated by Django 3.2.4 on 2021-07-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_alter_highlightbox_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightbox',
            name='alignment',
            field=models.CharField(choices=[('none', 'none'), ('right', 'right'), ('left', 'left')], default='none', max_length=10),
        ),
    ]
