# Generated by Django 3.2.13 on 2022-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_blogindexpage_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='teaser',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
