# Generated by Django 3.2.13 on 2022-05-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
