# Generated by Django 3.2.13 on 2022-11-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddl', '0002_basicpage_blogindexpage_blogpage_formfield_formpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='submit_label',
            field=models.CharField(default='submit', max_length=100),
            preserve_default=False,
        ),
    ]
