# Generated by Django 3.2.13 on 2022-11-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddl', '0004_knowledgepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepage',
            name='knowledge_root',
            field=models.BooleanField(default=False),
        ),
    ]
