# Generated by Django 3.2.17 on 2023-03-17 15:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('ddl', '0005_knowledgepage_knowledge_root'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body_top', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', icon='title')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('list', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(label='List'), icon='list-ul')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('highlight', wagtail.blocks.StructBlock([('title', wagtail.blocks.RichTextBlock()), ('text', wagtail.blocks.RichTextBlock()), ('background', wagtail.images.blocks.ImageChooserBlock(required=False)), ('alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'left'), ('right', 'right')]))]))], use_json_field=True)),
                ('body_bottom', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', icon='title')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('list', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(label='List'), icon='list-ul')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('highlight', wagtail.blocks.StructBlock([('title', wagtail.blocks.RichTextBlock()), ('text', wagtail.blocks.RichTextBlock()), ('background', wagtail.images.blocks.ImageChooserBlock(required=False)), ('alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'left'), ('right', 'right')]))]))], use_json_field=True)),
                ('include_news', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
