# Generated by Django 4.2.16 on 2025-02-25 14:12

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ddl', '0008_alter_landingpage_body_top'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('list', 3), ('image', 4), ('highlight', 8), ('button_link', 10)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'List'}), 3: ('wagtail.blocks.ListBlock', (2,), {'icon': 'list-ul'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.RichTextBlock', (), {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'left'), ('right', 'right')]}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('text', 5), ('background', 6), ('alignment', 7)]], {}), 9: ('wagtail.blocks.TextBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('link', 9), ('text', 9)]], {})}),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1), ('button_link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('link', 2), ('text', 2)]], {})}),
        ),
        migrations.AlterField(
            model_name='knowledgepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('list', 3), ('image', 4), ('highlight', 8), ('button_link', 10)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'List'}), 3: ('wagtail.blocks.ListBlock', (2,), {'icon': 'list-ul'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.RichTextBlock', (), {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'left'), ('right', 'right')]}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('text', 5), ('background', 6), ('alignment', 7)]], {}), 9: ('wagtail.blocks.TextBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('link', 9), ('text', 9)]], {})}),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='body_bottom',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('list', 3), ('image', 4), ('highlight', 8), ('button_link', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'List'}), 3: ('wagtail.blocks.ListBlock', (2,), {'icon': 'list-ul'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.RichTextBlock', (), {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'left'), ('right', 'right')]}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('text', 5), ('background', 6), ('alignment', 7)]], {}), 9: ('wagtail.blocks.TextBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('link', 9), ('text', 9)]], {})}),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='body_top',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('list', 3), ('image', 4), ('highlight', 8), ('button_link', 10)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'List'}), 3: ('wagtail.blocks.ListBlock', (2,), {'icon': 'list-ul'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.RichTextBlock', (), {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'left'), ('right', 'right')]}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('text', 5), ('background', 6), ('alignment', 7)]], {}), 9: ('wagtail.blocks.TextBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('link', 9), ('text', 9)]], {})}),
        ),
    ]
