# Generated by Django 4.2.26 on 2025-12-01 14:03

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ddl', '0009_delete_footer_alter_basicpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
