# Generated by Django 3.2.17 on 2024-05-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_pooled', '0006_delete_poolparticipant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PooledProject',
        ),
    ]
