name: Test Dev

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: ddmtestdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      env:
        DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
        DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
        DJANGO_DB_NAME: ddmtestdb
        DJANGO_DB_USER: root
        DJANGO_DB_PW: password
      run: |
        python manage.py migrate
        python manage.py collectstatic
    - name: Run Tests
      env:
        DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
        DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
        DJANGO_DB_NAME: ddmtestdb
        DJANGO_DB_USER: root
        DJANGO_DB_PW: password
      run: |
        python manage.py test

  merge-dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Merge dev -> stage
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch --all
          git pull --all
          git checkout stage
          git merge dev
          git push
